export const localImgUrl = {
"BTDEX" : "../img/dappPhoto/BTDEX.jpeg",
"Phoenix Wallet" : "../img/dappPhoto/PhoenixWallet.png",
"Burst Explorer" : "../img/dappPhoto/BurstExplorer.png",
"Cryptoball" : "../img/dappPhoto/cryptoball.jpeg",
"LMSI  Let-Me-Stake-It" : "../img/dappPhoto/LMSI.png",
"Babel Pool" : "../img/dappPhoto/BabelPool.png",
"Forex Zone Forum" : "../img/dappPhoto/ForexZoneForum.png",
"Million Burst Homepage" : "../img/dappPhoto/MillionBurstHomepage.png",
"burstkit4j" : "../img/dappPhoto/burstkit4j.jpeg",
"Gyra for Scavenger" : "../img/dappPhoto/GyraforScavenger.png",
"Burst Smart Contract Inspector" : "../img/dappPhoto/BurstSmartContractInspector.png",
"Burst Account Activator Service" : "../img/dappPhoto/BurstAccountActivatorService.png",
"Lev's Blockchain Explorer" : "../img/dappPhoto/LevsBlockchainExplorer.jpeg",
"Stellar Duel" : "../img/dappPhoto/StellarDuel.png",
"Blagominer" : "../img/dappPhoto/Blagominer.png",
"Goodplanet's Technology" : "../img/dappPhoto/GoodplanetsTechnology.png",
"Burst Ecosystem Monitor" : "../img/dappPhoto/BurstEcosystemMonitor.png",
"Wheel Of SIGNA" : "../img/dappPhoto/WheelOfSIGNA.jpeg",
"Open Burst Pool" : "../img/dappPhoto/OpenBurstPool.png",
"Signumcoin.ru Website of the Russian community" : "../img/dappPhoto/SignumcoinRuWebsiteOfTheRussianCommunity.jpeg",
"ShoutLoud!" : "../img/dappPhoto/ShoutLoud.png",
"Epicycle Signature" : "../img/dappPhoto/EpicycleSignature.png",
"KULCHA NFT Showcase dApplication " : "../img/dappPhoto/KULCHANFTShowcasedApplication.jpeg",
"Hotwallet" : "../img/dappPhoto/Hotwallet.svg",
"Engraver" : "../img/dappPhoto/Engraver.png",
"BurstLib" : "../img/dappPhoto/BurstLib.png",
"Proof of Burn" : "../img/dappPhoto/ProofofBurn.jpeg",
"TMG Cup 2022" : "../img/dappPhoto/TMGCup2022.jpeg",
" SIGNA Auto Commitment" : "../img/dappPhoto/SIGNAAutoCommitment.png",
"CloudBurst" : "../img/dappPhoto/CloudBurst.png",
"Public IP Address Auto Update for Signum Node" : "../img/dappPhoto/PublicIPAddressAutoUpdateforSignumNode.png",
"Scavenger" : "../img/dappPhoto/Scavenger.png",
"TurboPlotter 9000" : "../img/dappPhoto/TurboPlotter9000.jpeg",
"The Mining Game" : "../img/dappPhoto/TheMiningGame.png",
"SIGNUM DAPPS POOL" : "../img/dappPhoto/SIGNUMDAPPSPOOL.png",
"SignumArt" : "../img/dappPhoto/SignumArt.webp",
"Virtual HDD for mining ZTH tokens" : "../img/dappPhoto/VirtualHDDforminingZTHtokens.png",
"Signum Name System" : "../img/dappPhoto/SignumNameSystem.jpeg",
"ZTH Virtual Farm" : "../img/dappPhoto/ZTHVirtualFarm.png",
"SignaRank.Club" : "../img/dappPhoto/SignaRankClub.webp",
"Hall of RS-Addresses" : "../img/dappPhoto/HallofRSAddresses.png",
"Fomplo" : "../img/dappPhoto/Fomplo.webp",
"SignumJS" : "../img/dappPhoto/SignumJS.jpeg",
"NFT Game of 12 chairs" : "../img/dappPhoto/NFTGameof12chairs.png",
"XT Wallet" : "../img/dappPhoto/XTWallet.jpeg",
"TRT POOL" : "../img/dappPhoto/TRTPOOL.png",
"SmartC NFT" : "../img/dappPhoto/SmartCNFT.jpeg",
"SignumArt Mass Upload" : "../img/dappPhoto/SignumArtMassUpload.webp",
}