// ATTENTION: THESE ARE CLIENT SIDE VARS - DO NOT PUT SECRET HERE IN
import { PUBLIC_SAPPER_APP_IS_TESTNET,PUBLIC_SAPPER_APP_IS_MAINTENANCE,PUBLIC_SAPPER_APP_HOST_URL,PUBLIC_SAPPER_APP_CONTRACT_REFERENCE,PUBLIC_SAPPER_APP_MACHINE_CODE_HASH_IDS,
    PUBLIC_SAPPER_APP_CONTRACT_POLLING_INTERVAL_SECS, PUBLIC_SAPPER_APP_UNCONFIRMED_TX_POLLING_INTERVAL_SECS, PUBLIC_SAPPER_APP_DEEPLINK_REDIRECT_SERVICE_URL, PUBLIC_SAPPER_APP_TOKEN_WATCHER_INTERVAL_SECS,
    PUBLIC_SAPPER_APP_TOKEN_WATCHER_TIMEOUT_SECS, PUBLIC_SAPPER_APP_EXPLORER_URL, PUBLIC_SAPPER_APP_MAX_EARLY_ACCESS_BLOCK_HEIGHT, PUBLIC_SAPPER_APP_MAX_LEGACY_BLOCK_HEIGHT
 } from '$env/static/public';
export const Vars = {
    IsTestnet: PUBLIC_SAPPER_APP_IS_TESTNET === 'true',
    IsMaintenance: PUBLIC_SAPPER_APP_IS_MAINTENANCE === 'true',
    HostUrl: PUBLIC_SAPPER_APP_HOST_URL,
    ContractReference: PUBLIC_SAPPER_APP_CONTRACT_REFERENCE,
    // @ts-ignore
    ContractMachineCodeHashes: PUBLIC_SAPPER_APP_MACHINE_CODE_HASH_IDS.split(','),
    // @ts-ignore
    ContractPollingIntervalSecs: PUBLIC_SAPPER_APP_CONTRACT_POLLING_INTERVAL_SECS * 1000,
    UnconfirmedTxPollingIntervalSecs:
        // @ts-ignore
        PUBLIC_SAPPER_APP_UNCONFIRMED_TX_POLLING_INTERVAL_SECS * 1000,
    DeeplinkRedirectServiceUrl: PUBLIC_SAPPER_APP_DEEPLINK_REDIRECT_SERVICE_URL,
    TokenWatcherIntervalSecs: PUBLIC_SAPPER_APP_TOKEN_WATCHER_INTERVAL_SECS,
    TokenWatcherTimeoutSecs: PUBLIC_SAPPER_APP_TOKEN_WATCHER_TIMEOUT_SECS,
    ExplorerUrl: PUBLIC_SAPPER_APP_EXPLORER_URL,
    MaxEarlyAccessBlockHeight:  PUBLIC_SAPPER_APP_MAX_EARLY_ACCESS_BLOCK_HEIGHT,
    MaxLegacyBlockHeight: PUBLIC_SAPPER_APP_MAX_LEGACY_BLOCK_HEIGHT,
}
